version: '3.9'
services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: docker
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: locadora_jogos
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - 3308
    networks:
      - locadora-network
  locadora-jogos:
    image: ronyabreu/locadora-de-jogos
    restart: always
    build:
      context: .
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/locadora_jogos?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 12345
    ports:
      - "8080:8080"
    expose:
      - 8080
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - locadora-network
networks:
  locadora-network:
    driver: bridge