server:
  port: 80
security:
  jwt:
    secret-key: r0n1
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/locadora_jogos?useTimezone=true&serverTimezone=UTC
      username: root
      password: 12345
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
springdoc:
  pathsToMatch:
    - /api/v1/**
    - /usuario/**
    - /auth/**
  swagger-ui:
    use-root-path: true
cors:
  origins: http://localhost:8080,http://ronyelison.com.br,http://127.0.0.1:5500
file:
  upload-dir: /Users/ronye/Desktop/Java/UploadDir


