security:
  jwt:
    secret-key: r0n1
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rest_api?useTimezone=true&serverTimezone=UTC
      username: root
      password: 12345
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
springdoc:
  pathsToMatch:
    - /api/v1/**
    - /usuario/**
  swagger-ui:
    use-root-path: true
