security:
  jwt:
    secret-key: r0n1
spring:
  datasource:
      url: ${DATABASE_URL}
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 200MB
springdoc:
  pathsToMatch:
    - /api/v1/**
    - /usuario/**
    - /auth/**
  swagger-ui:
    use-root-path: true
cors:
  origins: http://localhost:8080,https://locadora-de-jogos.onrender.com/,http://127.0.0.1:5500
file:
  upload-dir: /Users/ronye/Desktop/Java/UploadDir


