name: Continuous-Integration with Github Actions

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application Jar
      working-directory: ./
      run: mvn clean package -DskipTests

    - name: Docker Compose Build
      working-directory: ./Locadora-de-Jogos
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/locadora-de-jogos:latest ${{ secrets.DOCKER_USERNAME }}/locadora-de-jogos:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/locadora-de-jogos:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/locadora-de-jogos:latest

      
